sudo: required
language: go
os:
  - linux
go:
  - 1.9

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - go get -v ./...
  - go build -v wolsrv.go
  - docker build -t cmaiorano/golang-wol:x86 -f Dockerfile.x86 .
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t cmaiorano/golang-wol:arm -f Dockerfile.arm .

after_success:
  - docker push cmaiorano/golang-wol:x86
  - docker push cmaiorano/golang-wol:arm

services:
  - docker